config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  devise_for :users, controllers:{registrations: 'registrations'}
  devise_scope :user do
    root to: 'home#index'
  end

  get '/chat/index'
  get '/chat/load_conversation/:id', to: 'chat#load_conversation'
  post '/chat/send_message/:id', to: 'chat#send_message'

  get '/user/index'

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

#last-end-anchor
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :sender, class_name: 'User'
  belongs_to :reciever, class_name: 'User'

  def self.all_messages_of(sender, reciever)
    where(sender: sender, reciever: reciever)
      .or(where(reciever: sender, sender: reciever))
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :message

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

before_action :authenticate_user!
  protect_from_forgery with: :exception
end

app/controllers/chat_controller.rb
class ChatController < ApplicationController
  def index

  end

  def load_conversation
    @user = User.find(params[:id])
    @messages = Message.all_messages_of(current_user, @user)
    render layout: false
  end

  def send_message
    @user = User.find(params[:id])
    @message = Message.create({sender: current_user, reciever: @user, message: params[:message]})
    render json: true
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:email, :password, :password_confirmation, :role)
  end

end

app/controllers/user_controller.rb
class UserController < ApplicationController

  def index
    @users = User.all.reject{|user| user ==  current_user}
    render :layout => false
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chat_helper.rb
module ChatHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/chat/_chat_list.html.erb
<div class="panel panel-default col-xs-6 col-md-4">
  <div class="panel-heading">
    <h3 class="panel-title">Select from below</h3>
  </div>
  <div>
    <div class="list-group" id="chat_list" style="height:500px; overflow: scroll;">

    </div>
  </div>
</div>

app/views/chat/_chat_list_js.js.erb
$(document).ready(function() {
  console.log("Onload");
});

app/views/chat/_conversation.html.erb
<div class="panel panel-default col-xs-12 col-md-8" id="conversation">
  Select a person on the left
</div>

app/views/chat/index.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Chat</h3>
  </div>
  <div class="panel-body">
    <%= render 'chat_list' %>
    <%= render 'conversation' %>
  </div>
</div>

app/views/chat/load_conversation.html.erb
<div class="panel-heading">
  <h3 class="panel-title">Conversation with <%= @user.email %></h3>
</div>

<ul class="list-group" style="height:500px; overflow: scroll;">
  <% for message in @messages %>
    <li class="list-group-item clearfix">
      <% if message.sender == @user %>
        <span>
      <% else %>
        <span class="pull-right">
      <% end %>
        <p><%= message.message %></p>
        <span class="glyphicon glyphicon-time"></span>
        <i class="text-muted"><%= time_ago_in_words(message.created_at.to_time) %></i>
      </span>
    </li>
  <% end %>
</ul>
<div class="panel-body">
  <div class="input-group">
    <input type="text" class="form-control" id="message" placeholder="Send a message...">
    <span class="input-group-btn">
      <button class="btn btn-default" type="button" onClick="send_message(<%= @user.id %>)">Send!</button>
    </span>
  </div>
</div>

app/views/home/index.html.erb
<h1>Welcome <%= current_user.email %>,</h1><br/>

<button type="button" class="btn btn-primary" onClick="window.location='<%= chat_index_path %>'">Chat </button>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChatHub</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav navbar-right">
            <% if current_user %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.email %> <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Logout", destroy_user_session_path, :method => 'delete' %></li>
                </ul>
              </li>
            <% else %>
              <li> Signin </li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/user/index.html.erb
<% for user in @users %>
  <li onClick="load_conversation_with(<%= user.id %>, this)" class="user-list list-group-item">
    <%= user.email %> <h6> <%= user.role %> </h6>
  </li>
<% end %>